fix ci/cd

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -65,14 +65,44 @@ jobs:
           encrypt        = true
           EOF
 
+      - name: Generate terraform.tfvars
+        working-directory: terraform
+        run: |
+          cat <<EOF > terraform.tfvars
+          acm_certificate_arn = "${{ secrets.CM_CERTIFICATE_ARN }}"
+          hosted_zone_id = "${{ secrets.HOSTED_ZONE_ID }}"
+          route53_record_name = "${{ secrets.ROUTE53_RECORD_NAME }}"
+          route53_record_value = "${{ secrets.ROUTE53_RECORD_VALUE }}"
+          EOF
+
       - name: Initialize Terraform
         working-directory: terraform
         run: terraform init -backend-config="backend-config.hcl"
 
       - name: Plan Terraform Changes
         working-directory: terraform
-        run: terraform plan
+        run: terraform plan -lock=false
 
       - name: Apply Terraform
         working-directory: terraform
-        run: terraform apply -auto-approve
+        run: terraform apply -auto-approve -lock=false
+
+      # - name: SSH and Update Container
+      #   working-directory: terraform
+      #   run: |
+      #     echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ./keys/id_rsa
+      #     chmod 600 ./keys/id_rsa  # Critical permission!
+
+      #     IP=$(terraform output -raw instance_public_ip)
+      #     echo "EC2 Public IP: $IP"
+      #     if [ -z "$IP" ]; then
+      #       echo "Error: Failed to get EC2 IP!"
+      #       exit 1
+      #     fi
+      
+      #     ssh -o ConnectTimeout=30 -o StrictHostKeyChecking=no -i ./keys/id_rsa ubuntu@$IP "
+      #     sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/fast-api-ec2:latest && \
+      #     sudo docker stop \$(sudo docker ps -q --filter ancestor=${{ secrets.DOCKERHUB_USERNAME }}/fast-api-ec2) || true && \
+      #     sudo docker run -d -p 8000:8000 ${{ secrets.DOCKERHUB_USERNAME }}/fast-api-ec2:latest
+      
+      #     rm -f ./keys/id_rsa
